CREATE DATABASE IF NOT EXISTS smart_school_system;
USE smart_school_system;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(30) NOT NULL,
  class_assigned VARCHAR(50) DEFAULT NULL,
  student_id VARCHAR(50) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS students (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  student_id VARCHAR(50) NOT NULL UNIQUE,
  name VARCHAR(150) NOT NULL,
  class VARCHAR(50) NOT NULL,
  section VARCHAR(10) DEFAULT 'A',
  gr_number VARCHAR(50) DEFAULT NULL,
  admission VARCHAR(50) DEFAULT NULL,
  student_password VARCHAR(255) DEFAULT NULL,
  parent VARCHAR(150) DEFAULT NULL,
  phone VARCHAR(20) DEFAULT NULL,
  parent_username VARCHAR(100) DEFAULT NULL,
  parent_access_key VARCHAR(20) DEFAULT NULL,
  parent_id VARCHAR(50) DEFAULT NULL,
  status VARCHAR(20) DEFAULT 'Active',
  fees VARCHAR(20) DEFAULT 'Pending',
  dob DATE DEFAULT NULL,
  gender VARCHAR(20) DEFAULT NULL,
  blood_group VARCHAR(10) DEFAULT NULL,
  address TEXT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY idx_students_gr_number (gr_number),
  KEY idx_students_class_section (class, section),
  CONSTRAINT fk_students_parent_username FOREIGN KEY (parent_username) REFERENCES users(username) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS teachers (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  emp VARCHAR(50) NOT NULL UNIQUE,
  subject VARCHAR(100) NOT NULL,
  class VARCHAR(50) DEFAULT NULL,
  division VARCHAR(10) DEFAULT NULL,
  phone VARCHAR(20) DEFAULT NULL,
  email VARCHAR(150) DEFAULT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'Active',
  teacher_id VARCHAR(50) DEFAULT NULL UNIQUE,
  teacher_password VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS classes (
  id VARCHAR(50) NOT NULL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  teacher VARCHAR(150) DEFAULT NULL,
  students INT DEFAULT 0,
  room VARCHAR(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS attendance (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  person_id VARCHAR(50) NOT NULL,
  person_type ENUM('student','teacher') NOT NULL,
  date DATE NOT NULL,
  status ENUM('P','A','L') NOT NULL DEFAULT 'P',
  class VARCHAR(50) DEFAULT NULL,
  section VARCHAR(10) DEFAULT NULL,
  subject VARCHAR(100) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY idx_attendance_person_date (person_id, person_type, date),
  KEY idx_attendance_class_date (class, date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS notifications (
  id VARCHAR(100) NOT NULL PRIMARY KEY,
  type VARCHAR(50) NOT NULL DEFAULT 'info',
  title VARCHAR(255) NOT NULL,
  body TEXT NOT NULL,
  class VARCHAR(50) DEFAULT NULL,
  section VARCHAR(10) DEFAULT NULL,
  student_id VARCHAR(50) DEFAULT NULL,
  student_name VARCHAR(150) DEFAULT NULL,
  is_read TINYINT(1) DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS timetable (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  class INT NOT NULL,
  section VARCHAR(10) NOT NULL,
  day VARCHAR(20) NOT NULL,
  lecture_num INT DEFAULT NULL,
  lecture VARCHAR(50) NOT NULL,
  subject VARCHAR(100) NOT NULL,
  teacher VARCHAR(150) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY idx_timetable_slot (class, section, day, lecture)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
